### ISSUE TITLE
from tss_utils import load_tss_model

### ISSUE THREAD

**Issue by hunglequoc2001** [TrustAI/GeoRobust#1]
Hi, i am interested about your work, but during the implementation process i notice that in many `*_main.py` files such as `mnist_main.py` has argument `--tss` and use file `tss_utils` to load tss model from the `TSS: Transformation-Specific Smoothing
for Robustness Certification` paper. I assume you do have it somewhere in original source code but it does not appear in the github version.
Can you upload it or show me how can i get `tss_utils` module?

**Comment by wangaxe** [comment]
Hi there, 

Sorry for the delay. At that time, I emailed the authors of `TSS: Transformation-Specific Smoothing for Robustness Certification` to request their models, and Linyi Li kindly shared the weights with me. 

You can find their models via the following link: https://drive.google.com/file/d/1tW4bTnoxlAFA0KeZGQdHr6Rr9weXJSDS/view

Best wishes
